package telas;

import classes.Caixa;
import classes.Cliente;
import classes.Funcionario;
import classes.Produto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaAcoes extends javax.swing.JFrame {
    double valorUnitario;
    int quantidade;
    Funcionario funcionario;
    Caixa caixa = new Caixa();
    Cliente cliente;
    
    public TelaAcoes() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/logoIcon.png")).getImage());
    }
    
    public void exportarFuncionario(Funcionario f){
        txtNome.setText(f.getNome());
        funcionario = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        tfNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfValorUnitario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        btnMaisValorUnitario = new javax.swing.JButton();
        btnMenosValorUnitario = new javax.swing.JButton();
        btnMaisQuantidade = new javax.swing.JButton();
        btnMenosQuantidade = new javax.swing.JButton();
        btnFinalizarCompra = new javax.swing.JButton();
        btnAdicionarAoCarrinho = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpListaCompras = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Mercado Orientado a Objetos");
        setPreferredSize(new java.awt.Dimension(830, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Funcionário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 120, 20);

        txtNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 20, 410, 20);

        tfNomeProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfNomeProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfNomeProduto);
        tfNomeProduto.setBounds(30, 190, 320, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_MS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 270, 110);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Valor Unitário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 240, 150, 30);

        tfValorUnitario.setEditable(false);
        tfValorUnitario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfValorUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorUnitario.setText("1.00");
        tfValorUnitario.setToolTipText("Valor em R$");
        getContentPane().add(tfValorUnitario);
        tfValorUnitario.setBounds(110, 270, 130, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nome do Produto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 160, 180, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 320, 150, 30);

        tfQuantidade.setEditable(false);
        tfQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfQuantidade.setText("1");
        getContentPane().add(tfQuantidade);
        tfQuantidade.setBounds(130, 350, 70, 40);

        btnMaisValorUnitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMais.png"))); // NOI18N
        btnMaisValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisValorUnitarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaisValorUnitario);
        btnMaisValorUnitario.setBounds(240, 270, 40, 40);

        btnMenosValorUnitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMenos.png"))); // NOI18N
        btnMenosValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosValorUnitarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenosValorUnitario);
        btnMenosValorUnitario.setBounds(70, 270, 40, 40);

        btnMaisQuantidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMais.png"))); // NOI18N
        btnMaisQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaisQuantidade);
        btnMaisQuantidade.setBounds(200, 350, 40, 40);

        btnMenosQuantidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMenos.png"))); // NOI18N
        btnMenosQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenosQuantidade);
        btnMenosQuantidade.setBounds(90, 350, 40, 40);

        btnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnFinalizarCompra.png"))); // NOI18N
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarCompra);
        btnFinalizarCompra.setBounds(470, 410, 220, 40);

        btnAdicionarAoCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnAdicionarAoCarrinho.png"))); // NOI18N
        btnAdicionarAoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAoCarrinhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarAoCarrinho);
        btnAdicionarAoCarrinho.setBounds(50, 410, 250, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(740, 30, 50, 50);

        tpListaCompras.setEditable(false);
        tpListaCompras.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jScrollPane1.setViewportView(tpListaCompras);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 140, 430, 260);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Lista de Compras");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 110, 150, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_sistema.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 830, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnMenosValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosValorUnitarioActionPerformed
       valorUnitario = Double.parseDouble(tfValorUnitario.getText());
       if(valorUnitario>1){
           valorUnitario-=0.5f;
       tfValorUnitario.setText(String.valueOf(valorUnitario));
       }
    }//GEN-LAST:event_btnMenosValorUnitarioActionPerformed

    private void btnMaisValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisValorUnitarioActionPerformed
        valorUnitario = Double.parseDouble(tfValorUnitario.getText());
        valorUnitario+=0.5f;
        tfValorUnitario.setText(String.valueOf(valorUnitario));
    }//GEN-LAST:event_btnMaisValorUnitarioActionPerformed

    private void btnMenosQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosQuantidadeActionPerformed
        quantidade = Integer.parseInt(tfQuantidade.getText());
        if(quantidade>1){
            quantidade--;
            tfQuantidade.setText(String.valueOf(quantidade));
        }
    }//GEN-LAST:event_btnMenosQuantidadeActionPerformed

    private void btnMaisQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisQuantidadeActionPerformed
        quantidade = Integer.parseInt(tfQuantidade.getText());
        quantidade++;
        tfQuantidade.setText(String.valueOf(quantidade));
    }//GEN-LAST:event_btnMaisQuantidadeActionPerformed

    private void btnAdicionarAoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAoCarrinhoActionPerformed
        
        
        String nomeProduto = tfNomeProduto.getText();
        if(nomeProduto.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, preencha o nome do produto antes de prosseguir!");
        }else{
            double valorUnitarioProduto = Double.parseDouble(tfValorUnitario.getText());
            int quantidadeProduto = Integer.parseInt(tfQuantidade.getText());

            Produto produto = new Produto(nomeProduto, valorUnitarioProduto, quantidadeProduto);

            caixa.adicionarProdutoACompra(produto);
            tfNomeProduto.setText("");
            tfQuantidade.setText(String.valueOf(1));
            tfValorUnitario.setText(String.valueOf(1.00));
            tpListaCompras.setText(caixa.mostrarProdutos());
        }
    }//GEN-LAST:event_btnAdicionarAoCarrinhoActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        if(caixa.mostrarProdutos().equals("")){
            JOptionPane.showMessageDialog(null, "Adicione ao menos um produto a compra antes de Prosseguir!");
        } else{
            try{
            String nomeCliente = JOptionPane.showInputDialog("Digite o nome do Cliente:");
            double valorPagoCliente = Double.parseDouble(JOptionPane.showInputDialog("Qual o valor dado por " + nomeCliente + " ?"));
            cliente = new Cliente(nomeCliente, valorPagoCliente);
            if(caixa.pagar(cliente)){
                JOptionPane.showMessageDialog(null, "Pagamento aprovado!\nGerando nota fiscal...");
            }else{
                JOptionPane.showMessageDialog(null, "O valor pago pelo cliente é insuficiente para receber a compra!\nSaiba mais com a nota fiscal.");
            }
            
            TelaNotaFiscal telaNotaFiscal = new TelaNotaFiscal();
            telaNotaFiscal.exportarDadosParaNotaFiscal(funcionario, cliente, caixa);
            telaNotaFiscal.setVisible(true);
            dispose();
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor, digite um valor válido!\nA compra ainda não foi concluida!");
        }catch(NullPointerException e){
                btnFinalizarCompraActionPerformed(evt);
        }
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAdicionarAoCarrinho;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnMaisQuantidade;
    private javax.swing.JButton btnMaisValorUnitario;
    private javax.swing.JButton btnMenosQuantidade;
    private javax.swing.JButton btnMenosValorUnitario;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfNomeProduto;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfValorUnitario;
    private javax.swing.JTextPane tpListaCompras;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
